### PR TITLE
WIP macros are stages that do not deploy code

### PR DESCRIPTION
**Pull request by grosser**
/cc @zendesk/samson

turning macro into a stage with type=Macro ... which gets rid of a lot of duplication and also make macros audited since they keep track of their deploys

keeping old macro tables for a while to make sure we can roll back

screen shot 2016-03-22 at 8 39 49 pm

### Risks
- Medium: macro thing blowing up
- Medium: some views showing macros when they should not

### CODE REVIEW

**Comment by henders** [comment]
Nice, looking forward to this one :heart:

**Comment by grosser** [comment]
screen shot 2016-04-12 at 3 01 34 pm

**Comment by grosser** [comment]
all good now! :D

**Comment by grosser** [comment]
closing since I'm not actively working on this now ...

**Pull request closed without merging**
