### PR TITLE
Update githubstatus url

### PR DESCRIPTION
**Pull request by rcclemente**
`status.github.com` has been deprecated

/cc @zendesk/samson

### Tasks
 - [ ] :+1: from team

### References
 
screen shot 2018-12-12 at 2 18 38 pm

### Risks
- Level: Low

### CODE REVIEW

**Comment by grosser** [comment]
can you fix `bin/rails test test/lib/samson/periodical_test.rb:215`
(the other periodical test is know red on master... fix coming /cc @ragurney)

**Comment by grosser** [comment]
https://www.githubstatus.com/api/v2/status.json works see https://www.githubstatus.com/api

**Comment by grosser** [comment]
sent an issue to github on the lack of docs and backwards compatability

**Comment by rcclemente** [comment]
@grosser updated the test, since it still has issues i wont merge this yet

**Comment by grosser** [comment]
heard back from github support and they said they'd maybe fix the api diff in a future version 🤷‍♂️

**Comment by nick-f** [comment]
Periodic brownouts are now happening and the site will be turned off on March 4th.

image

**Comment by grosser** [comment]
I'll fix it soon

**Comment by grosser** [comment]
will be fixed in https://github.com/zendesk/samson/pull/3240

**Pull request closed without merging**
