### PR TITLE
show missing config variables

### PR DESCRIPTION
**Pull request by grosser**
screen shot 2018-01-19 at 2 59 37 pm
screen shot 2018-01-19 at 2 59 32 pm
screen shot 2018-01-19 at 3 22 44 pm
screen shot 2018-01-19 at 3 22 50 pm
screen shot 2018-01-19 at 3 36 42 pm

@jonmoter @dragonfax

### CODE REVIEW

**Comment by jonmoter** [comment]
When displaying ENV vars, let's have a table that displays:

* name of ENV var
* project or env var group
* current value
* last person who modified the value
* link to project or ENV var group

**Comment by jonmoter** [comment]
For secrets, also display in a table, and include creator and link to create a new a new secret for the missing deploy group.

**Comment by grosser** [comment]
screen shot 2018-01-22 at 3 29 41 pm

**Comment by grosser** [comment]
- link to last updater is a lot of copy-pasted logic that's hard to pull into controller
 - env link goes to project or group ... history is linked there
 - secret link goes to secret, history is shown there

**Comment by grosser** [comment]
screen shot 2018-01-22 at 3 49 24 pm

added the 'create similar' button to secrets show to make creating a new secret easy

**Comment by grosser** [comment]
screen shot 2018-01-22 at 5 32 18 pm

**Comment by ubootda** [comment]
👍  thanks michael!

**Pull request merged**
