### PR TITLE
Correct fix for Slack @here notifications

### PR DESCRIPTION
**Pull request by andreionut**
* I've enabled Slack message full parsing mode
* This way, Slack can deal with the formatting an we just write the messages like in a chat text box

/cc @zendesk/samson @grosser @zehua 

### Tasks
 - [ ] :+1: from team

### References
 - https://api.slack.com/docs/message-formatting#parsing_modes

### Risks
- Level: Low

### CODE REVIEW

**Comment by grosser** [comment]
👍

**Comment by zehua** [comment]
I thought we would disable html encoding on the text (see https://api.slack.com/docs/message-formatting#how_to_escape_characters).

But this way also works. Should we use `link_names: 1` instead of `parse: full` so that other formatting such as links would still work?

**Comment by zehua** [comment]
👍  after fixing merge conflicts

**Comment by andreionut** [comment]
@zehua `parse: full` parses all the message, from mentions to links and we want to have that `@here` become a mention.
I tried to disable html encoding, but it was done in a JS function shared by all the buddy check plugins somehow.
I think this is the best approach as it allows people to write the message as they would in a Slack text box, no more magic tags that we have to whitelist.

**Comment by zehua** [comment]
> parse: full parses all the message, from mentions to links and we want to have that @here become a mention.

yeah, `parse: full` will turn `@here` into a mention. But it will also encode `<http://link.com|link text>` and not show it as a link.

**Comment by andreionut** [comment]
Think this: https://github.com/zendesk/samson/pull/1206 conflicts tis PR, so I'm going to revert mine

**Pull request merged**
