### PR TITLE
Change flowdock plugin message for approval

### PR DESCRIPTION
**Pull request by pschambacher**
:phone::feet:

/cc @zendesk/samson @zendesk/voice 

### Description
 * taking advantage of Markdown to make the link take less room in the message
 * display which reference is being deployed
 * use Markdown again to make reference bold

### Steps to merge
* [ ] :+1: from the team

### Risks
* Low: failure to post flowdock message when deploying

### CODE REVIEW

**Comment by davecocoa** [comment]
This is awesome! :+1: For me.

One nitpick you can totally ignore if you want: I don't like "here" as link text, it's not descriptive, I would prefer to have `[Approve deploy](#{project_deploy_url(deploy.project, deploy)})`

**Comment by davecocoa** [comment]
Watch out for conflict with this other PR though... https://github.com/zendesk/samson/pull/623/files

**Comment by pschambacher** [comment]
@davecocoa Good idea :haircut:

**Comment by davecocoa** [comment]
:+1: nice!

**Comment by ciaranarcher** [comment]
:+1:

**Pull request merged**
