### PR TITLE
show errors on staging

### PR DESCRIPTION
**Pull request by grosser**
debugging staging

### CODE REVIEW

**Comment by sandlerr** [comment]
is something eating errors before they make it to the log file?

**Comment by grosser** [comment]
this is showing them in the UI, not the log files -> faster debugging

**Comment by sandlerr** [comment]
alright, thought this might have been a workaround for inadequate logs :+1:

**Comment by grosser** [comment]
logs were fine ... but constantly going to the server is annoying ...
the airbrake UI change alone would fix that ... but why not be even lazier :D

**Pull request merged**
