### PR TITLE
PAAS-210 make builds optional

### PR DESCRIPTION
**Pull request by grosser**
@zendesk/paas 

when a repo has no Dockerfile, allow it to be deployed, but do not try to build it.

### CODE REVIEW

**Comment by irwaters** [comment]
lgtm 👍

**Comment by grosser** [comment]
local builds seems to work fine too :)

**Comment by rata** [comment]
@grosser seems fine. But I'm not sure I follow. When will you mark a project to deploy with kubernetes and have no Dockerfile?
I understand that you may want to build the docker image outside samson, but this is not what this patch is doing, right?

**Comment by grosser** [comment]
We have some services that will use prebuilt images where we don't have the
original source ... and this way we can deploy them the same way to all our
servers

**Comment by rata** [comment]
On Sat, Jun 18, 2016 at 11:19:09AM -0700, Michael Grosser wrote:
> We have some services that will use prebuilt images where we don't have the
> original source ... and this way we can deploy them the same way to all our
> servers

Oh, cool. But this doesn't make possible to deploy a project with a dockerfile
which has been built in some other place (like travis or the devs pc), right?

Just to understand, the change seems totally fine! :)

**Comment by grosser** [comment]
Nah ... but could be en enhancement down the line ... we might as well have
a 'don't build' flag on the project ... for now I think this is a nice
change anyway since it would just fail when there was no dockerfile
otherwise

**Comment by rata** [comment]
On Sat, Jun 18, 2016 at 12:54:26PM -0700, Michael Grosser wrote:
> Nah ... but could be en enhancement down the line ... we might as well have
> a 'don't build' flag on the project ... for now I think this is a nice
> change anyway since it would just fail when there was no dockerfile
> otherwise

Totally agree

**Comment by grosser** [comment]
update to also make builds ref and sha not-null since that is what the migration implicitly depends on anyway

**Pull request merged**
