### PR TITLE
PAAS-5085 add input for namespace metadata so we can track team/proje…

### PR DESCRIPTION
**Pull request by grosser**
…ct/product

Screen Shot 2019-10-30 at 9 46 59 AM

@zendesk/compute 

### Risks
 - Low: namespace getting modified by accident/breaking other tools/integrations

### CODE REVIEW

**Comment by uthark** [comment]
Does it support env substitution? We may want to have different labels per cluster/deploy group.

**Review by uthark — APPROVED** [review]

**Comment by grosser** [comment]
- so far nobody wanted different labels per cluster ... so I'd leave that for next PR
 - not sure what "values from git" is, but it only patches, so it will merge with existing values from the cluster ... for example it will not remove labels/annotations that are already set, but override them when they are set

**Comment by uthark** [comment]
Ok, one more question - what about annotations/labels created by different controllers? update should be a PATCH ideally.

**Comment by grosser** [comment]
- yes in the db
 - db is easier since that's where the name is stored too ... we can talk about moving config into git, but that's a different usecase / not in scope for this change 🤷‍♂

**Comment by grosser** [comment]
"annotations/labels created by different controllers" will not be touched since it uses "PATCH"

**Pull request merged**
