### PR TITLE
faster docker build

### PR DESCRIPTION
**Pull request by sandlerr**
@zendesk/runway @zendesk/samson

### CODE REVIEW

**Comment by sandlerr** [comment]
We should be careful with `mkdir` in Dockerfiles, it seems to bust the cache unless we change the mtime.

**Comment by grosser** [comment]
:+1: yeah ... that bug is annoying :/

**Comment by grosser** [comment]
will be fixed in 1.8 https://github.com/docker/docker/pull/12031

**Comment by sandlerr** [comment]
glad they changed that. Let's revert this when 1.8 is out.

**Comment by princemaple** [comment]
OMG I'm so looking forward to 1.8 now.

**Pull request merged**
