### PR TITLE
SAMSON-299 avoid giant commits params we get from github ... they break syslog

### PR DESCRIPTION
**Pull request by grosser**
simple/cheap solution ... ideally compare size and truncate as needed, but maybe this is good enough ?

https://zendesk.atlassian.net/browse/SAMSON-299

@jonmoter @murat1985

### CODE REVIEW

**Comment by murat1985** [comment]
👍

**Comment by murat1985** [comment]
that is quiet strange to have information that available on a github additionally in syslog. Does it really needed for troubleshooting or retrospective analysis ?

**Comment by jonmoter** [comment]
Have you verified this works?

The lograge code you're modifying there says that it should strip out the {{%w[format action controller]}}, but I see those parameters appearing in the bug linked above.  So I'm not confident that's working the way we think it should

**Comment by grosser** [comment]
hmm true ... must be coming from somewhere else :/

**Comment by jonmoter** [comment]
Or maybe the keys to `event.payload[:params]` are symbols instead of strings?

**Comment by grosser** [comment]
ah they appear but not as part of the params, so this should be right

**Pull request merged**
