### PR TITLE
Include new env variable with the stage name (permalink)

### PR DESCRIPTION
**Pull request by pschambacher**
/cc @henders @fneves @stubotnik @lukkry

### CODE REVIEW

**Comment by sandlerr** [comment]
@pschambacher what are you going to use this for? We've already got the DEPLOY_URL if you need to send it around.

**Comment by sandlerr** [comment]
I'm guessing relates to https://github.com/zendesk/samson/pull/519?

**Comment by pschambacher** [comment]
@sandlerr It's related but I also want to get this name to call a webhook who needs to know which stage was just deployed to chain the next one

**Comment by sandlerr** [comment]
Does https://github.com/zendesk/samson/pull/425 meet your needs?

**Comment by pschambacher** [comment]
@sandlerr Yeah I had a chat with Shane about it. Closing now.

**Pull request closed without merging**
