### PR TITLE
PAAS-425 do not override kube-system namespace, it is unique for every cluster

### PR DESCRIPTION
**Pull request by grosser**
@jonmoter

### CODE REVIEW

**Comment by grosser** [comment]
need to rework this ... we use namespace in a few places when querying for jobs/services etc ... so the release_doc has to change ... which will mean the release_doc no longer matches the deploy group which is kind of weird ...

**Comment by grosser** [comment]
rebased on the latest cleanup PR ... that should do the trick ...
it will still be a little weird that the namespace does not match, but thats better then having an extra deploy group for all clusters ...

**Comment by jonmoter** [comment]
Could you rebase this after you merge #1337?

**Comment by grosser** [comment]
done

**Pull request merged**
