### PR TITLE
Update kubeclient to work with k8s 1.2.0

### PR DESCRIPTION
**Pull request by rata**
/cc @zendesk/samson

### Tasks
 - [ ] :+1: from team

### References
 - Jira link:

### Risks
- Level: Low

kubeclient fixed it in this commit:
	https://github.com/abonas/kubeclient/commit/03e507b353aec137bf8daaecde78aef2dd5a698d

And using the latest version fixes using a k8s 1.2.x cluster with samson

### CODE REVIEW

**Comment by grosser** [comment]
👍

**Comment by rata** [comment]
@grosser don't know why travis fails. Here bundle install works just fine. Do you know?

**Comment by grosser** [comment]
missing gem in vendor/cache -> `bundle package`

**Comment by rata** [comment]
@grosser fixed now!

**Pull request merged**
