### PR TITLE
move kubernetes angular code into kubernetes folder

### PR DESCRIPTION
**Pull request by grosser**
@zendesk/paas this seems to all be unused / builds tab works fine without ...

### CODE REVIEW

**Comment by grosser** [comment]
@sbrnunes

**Comment by grosser** [comment]
this is all only used in kubernetes part ... so moving it there ... how about deleting all that kubernetes js now that we have a proper deploy flow ? :trollface:

**Comment by jonmoter** [comment]
👍

**Comment by sbrnunes** [comment]
Sorry @grosser, I was on PTO last week, I'm just getting through my email. 

Yep, this code was only used by the Kubernetes AngularJS screens. However, because they were not specific for the Kubernetes plugin, i.e., this code could be reused anywhere, I placed it in the core.

**Pull request merged**
