### PR TITLE
show deploy on release checkbox when a branch is configured, no need …

### PR DESCRIPTION
**Pull request by grosser**
…to wait for first release

I was confused why the box did not show up :/

@zendesk/samson @zendesk/compute

### CODE REVIEW

**Comment by yizhang-zen** [comment]
Silly questions: Will the deploy branches show up? Do we really need the deploy branches to choose from, why not waiting and use release?

**Comment by grosser** [comment]
the release branch gets set in the project edit `master` mostly ... once it's set stages can start deploying when a new commit is pushed to that branch

**Comment by yizhang-zen** [comment]
True. But will it confuse people when showing a bunch of deploy branches?

**Comment by grosser** [comment]
this is not about deploy branches

**Pull request merged**
