### PR TITLE
need more room for longer env var values

### PR DESCRIPTION
**Pull request by grosser**
got some public keys in there now and 255 is not cutting it :(

### CODE REVIEW

**Comment by jonmoter** [comment]
If someone tries to paste something longer than the string limit, do they get an error in the UI?

**Comment by grosser** [comment]
worked on localhost but not the servers ... working on that in parallel ... something fishy about strict mode

**Comment by jonmoter** [comment]
As long as we're at it, want to give a little more room, like 2048?

Using a `TEXT` field is probably overkill...

**Comment by grosser** [comment]
updated

**Pull request merged**
