### PR TITLE
Environment variables for project stages

### PR DESCRIPTION
**Pull request by sathishavm**
User can add environment variables specific to each stage in project, This allows multiple configurations for the same deploy group.
Stage environment-variables can add both in projects and stages edit pages.

**Projects Edit Page**

Screen Shot 2019-03-11 at 11 20 18 PM

**Stages Edit Page**

Screen Shot 2019-03-11 at 11 21 41 PM

/cc @zendesk/samson

### CODE REVIEW

**Review by grosser — CHANGES_REQUESTED** [review]
- should only be editable in a single place
 - afaik edit via stage-edit would be simpler to implement and not require adding stage logic to so many places

**Review by grosser — COMMENTED** [review]
use https://github.com/zendesk/samson/pull/2666 as template, it's much simpler / needs fewer changes (no need for a new plugin, maybe just put the env var stuff into env plugin directly too)

**Comment by sathishavm** [comment]
The stage env logic is only in env plugin, just like deploy and project env, rather than creating a new plugin.
The reason we have the stage env both in the project edit page and stage edit page, so that it is more reliable and the user has more understanding about the priority and changes to the env.
The deploy_env plugin is much more simpler, as we can't able to edit the environment variables once the deploy is finished.
Along with this, I have converted the usage of plugins inside the application to hooks.

**Comment by grosser** [comment]
Yes, it should not be a new plugin 👍 
Having multiple edit UIs for the same data does not sound "more reliable" to me, but confusing / error-prone. Let's do the "plugin conversion" and "deploy env -> env" first, so this will be a smaller PR, I'll give it a try and see if it's simple.

**Comment by grosser** [comment]
https://github.com/zendesk/samson/pull/3234 works and is dead-simple ... let's do that instead

**Pull request closed without merging**
