### PR TITLE
do not ignore build updates when they come in in rapid succession

### PR DESCRIPTION
**Pull request by grosser**
@jonmoter @ragurney @dndungu 

should take care of most gcr-watcher sisues ...
and if not we got https://github.com/zendesk/samson/pull/2508

### CODE REVIEW

**Comment by jonmoter** [comment]
So the issue is that when two POSTs from gcr_watcher came in rapid succession, and they were being processed at the same time?

I thought the way gcr_watcher worked, it would wait for one POST to Samson to return before sending the next one.

**Comment by grosser** [comment]
does not seem to do that ... saw the same request except with a different
status coming in right after each other and the second one failed with
uniquness
I'll debug this a bit more tomorrow, still need to verify rebuild work in
prod anyway

**Comment by grosser** [comment]
definitely not working, requests came in 1s apart and the first request took 4s to finish

2018-01-29T23:14:09.887Z ... duration":3819.98
2018-01-29T23:14:10.941Z

**Comment by grosser** [comment]
I think this is a good pattern in general since we had the same issue already when `release branch` and `deploy on release` tried to create builds at the same time

**Pull request merged**
