### PR TITLE
show kubernetes resources and limits on project page

### PR DESCRIPTION
**Pull request by grosser**
@jonmoter @dragonfax

### CODE REVIEW

**Comment by grosser** [comment]
screen shot 2017-12-27 at 5 23 34 pm
screen shot 2017-12-28 at 2 21 08 pm
screen shot 2017-12-28 at 2 23 32 pm

**Comment by dragonfax** [comment]
2 screenshots not working?

**Comment by grosser** [comment]
just markdown issue

**Comment by grosser** [comment]
This also includes simplification from "Deploy Group Roles" -> "Resources" and "Usage Limits" -> "Limits" ... renaming the tables is harder, so that must be enough for now :)

**Comment by jonmoter** [comment]
Looks good! 👍

**Pull request merged**
