### PR TITLE
bump ldap to avoid http://osvdb.org/show/osvdb/106108

### PR DESCRIPTION
**Pull request by grosser**
Name: net-ldap
Version: 0.3.1
Advisory: OSVDB-106108
Criticality: Low
URL: http://osvdb.org/show/osvdb/106108
Title: Net::LDAP for Ruby lib/net/ldap/password.rb SSHA Password Generation Weak Salt
Solution: upgrade to >= 0.6.0

@zendesk/runway 

### Risks
 - Medium: ldap failing

### CODE REVIEW

**Comment by grosser** [comment]
@zendesk/runway

**Comment by steved** [comment]
It's not urgent, let's just wait until it's released.

**Comment by henders** [comment]
Aye, agree with that. Linking to the master branch on a git repo is asking for more trouble then it fixes IMO.

**Comment by grosser** [comment]
finally got them to do a real release ... good to go ?

**Comment by henders** [comment]
Cool! :+1:

**Pull request merged**
