### PR TITLE
Fix k8s deployment

### PR DESCRIPTION
**Pull request by rata**
/cc @zendesk/samson

### Tasks
 - [ ] :+1: from team

### References
 - Jira link:

### Risks
- Level: Low

### CODE REVIEW

**Comment by grosser** [comment]
isn't it nice to be able to query deploys by tag ?

the issue is writing it to the env again ?

**Comment by rata** [comment]
@grosser query how?

The except is to not match it when doing a deploy, if not it will not replace the old version as the revision/tag are different (as they are supposed to, they are different version because they are different deploys). It's just to match which pods to replace, IIUC

**Comment by grosser** [comment]
ah yes

**Comment by grosser** [comment]
should be a .slice then since we don't want to put anything in there by accident ?
also some test that makes sure nothing gets added ...

**Comment by grosser** [comment]
I'll put that into my PR as well ... should be done soon ...

**Comment by rata** [comment]
@grosser oh, thanks! Let me know when it is merged! Thanks =)

**Pull request closed without merging**
