### PR TITLE
Fixed Bitbucket authentication

### PR DESCRIPTION
**Pull request by bobbrodie**
Bitbucket authentication was not working. Ultimately the fix is for omniauth-bitbucket to merge in robzdc's changes, but we won't have control over that.

/cc @zendesk/samson

### Tasks
 - [ ] :+1: from team

### References
 - Jira link:

### Risks
- Level: Low/Med/High

### CODE REVIEW

**Comment by grosser** [comment]
please link the PR too, would prefer if we can point this to a branch

**Comment by grosser** [comment]
also bundle so the lockfile updates ... ideally add a test, but not sure how to really test this ...
next best thing add a escription of how to reproduce the error and when it is ok to remove this

**Comment by bobbrodie** [comment]
`please link the PR too, would prefer if we can point this to a branch`
I'm not sure what we should to link it to? There's no open issue for this specifically , and it came from a fork so there's no separate branch.

`also bundle so the lockfile updates ... ideally add a test, but not sure how to really test this ...
next best thing add a escription of how to reproduce the error and when it is ok to remove this`
The Gemfile lock has been added. There shouldn't need to be any new tests. Maybe in the future once the auth integrations are pluggable each could have its own suite of tests that provide better coverage? I believe the only Bitbucket-specific tests that exist are in the sessions controller. The error we were running into was this:

1. Use Bitbucket as your authentication scheme (and configure your oAuth)
2. Go to the app
3. Click _Login with Bitbucket_
4. Click _Grant Access_

```
uninitialized constant OmniAuth::Strategies::Bitbucket::MultiJson

bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
bootsnap (1.3.0) lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
omniauth-bitbucket (0.0.2) lib/omniauth/strategies/bitbucket.rb:32:in `raw_info'
omniauth-bitbucket (0.0.2) lib/omniauth/strategies/bitbucket.rb:20:in `block in <class:Bitbucket>'
omniauth (1.6.1) lib/omniauth/strategy.rb:108:in `instance_eval'
omniauth (1.6.1) lib/omniauth/strategy.rb:108:in `block in compile_stack'
omniauth (1.6.1) lib/omniauth/strategy.rb:107:in `each'
omniauth (1.6.1) lib/omniauth/strategy.rb:107:in `inject'
omniauth (1.6.1) lib/omniauth/strategy.rb:107:in `compile_stack'
omniauth (1.6.1) lib/omniauth/strategy.rb:101:in `uid_stack'
omniauth (1.6.1) lib/omniauth/strategy.rb:321:in `uid'
omniauth (1.6.1) lib/omniauth/strategy.rb:337:in `auth_hash'
omniauth (1.6.1) lib/omniauth/strategy.rb:360:in `callback_phase'
omniauth-oauth (1.1.0) lib/omniauth/strategies/oauth.rb:57:in `callback_phase'
omniauth (1.6.1) lib/omniauth/strategy.rb:230:in `callback_call'
omniauth (1.6.1) lib/omniauth/strategy.rb:187:in `call!'
omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
omniauth (1.6.1) lib/omniauth/builder.rb:63:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.0) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
rack-mini-profiler (0.10.2) lib/mini_profiler/profiler.rb:282:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.3) lib/puma/configuration.rb:225:in `call'
puma (3.11.3) lib/puma/server.rb:624:in `handle_request'
puma (3.11.3) lib/puma/server.rb:438:in `process_client'
puma (3.11.3) lib/puma/server.rb:302:in `block in run'
puma (3.11.3) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by grosser** [comment]
can you turn this fork into a PR then (to share/get it merged) ?
this is the commit that fixes it ? https://github.com/robzdc/omniauth-bitbucket/commit/688c5e564aa53402d73a207fe37e7cdfc54989e9
that commit also could use tests in the repo

the error sounds more like `require 'multi_json'` is missing, can we just add that to the initializer ? config/initializers/omniauth.rb:60

**Pull request closed without merging**
