### PR TITLE
Fix formatting for Slack messages

### PR DESCRIPTION
**Pull request by gstamp**
Unfortunately there's a problem with the formatting of slack notifications in my previous PR. This fixes things so we get correctly formatted output.

image

### CODE REVIEW

**Comment by sandlerr** [comment]
Sure, mind updating the tests?

**Comment by sandlerr** [comment]
:+1:

**Comment by sandlerr** [comment]
cc @zendesk/samson

**Comment by zendesk-shender** [comment]
:+1:

**Pull request merged**
