### PR TITLE
add SECRET_PULLER_TYPE to migrate to secret-sidecar

### PR DESCRIPTION
**Pull request by rbayerl**
Modify init container when `SECRET_PULLER_TYPE` is set to `secret-sidecar`.

### Risks
- Low

### CODE REVIEW

**Review by grosser — APPROVED** [review]

**Comment by rbayerl** [comment]
Any idea what these failed `GitRepository` checks are all about? They seem unrelated to my change.

**Comment by grosser** [comment]
bundle_audit regularly fails but that's not your fault

**Comment by grosser** [comment]
GitRepository should not fail ... but I can take a look if you can reproduce

**Comment by rbayerl** [comment]
It's weird the tests seem flaky...e.g. test sqlite one of my tests pass but it fails on mysql and postgres. All of them have the GitRepository failure.

**Comment by grosser** [comment]
new to me and passes locally ... so just add a `skip` 😞

**Comment by grosser** [comment]
```
skip "Somehow broken on CI" if ENV["CI"]
```

**Comment by grosser** [comment]
let me fix them all in https://github.com/zendesk/samson/pull/4033#pullrequestreview-1171043289 and then you can have a clean PR :)

**Comment by grosser** [comment]
rebase 🤞

**Pull request merged**
