### PR TITLE
improve redeploy on error logic

### PR DESCRIPTION
**Pull request by grosser**
- do not re-deploy the same sha when deploy failed
 - do not declare success when deploy failed
 - improve DeployService test coverage

@zendesk/compute @zendesk/samson

### CODE REVIEW

**Comment by uthark** [comment]
> do not re-deploy the same sha when deploy failed

What about CPU/Memory request/limit changes? If I modify them, I should be able to try deploy again with the same SHA. (i.e. because error was of incorrect req/limits)

**Comment by grosser** [comment]
deploying the old deploy would not revert that since we do not persist these values per deploy
only thing that might be worth checking is per-deploy env vars, but that's a underused feature anyway ...

**Comment by adammw** [comment]
i think that's a vital feature (the env vars). if it's a configuration change that's the issue, it should revert that...

**Comment by adammw** [comment]
don't you already have them serialised in the deploy?

**Comment by grosser** [comment]
we don't use "deploy env vars" only thing we use is stage/project env vars and they are not stored per deploy

**Comment by grosser** [comment]
we serialize some "env state" but that's not really deployable ... also deploy env vars change rarely and user has to opt-in to the redeploy anyway

**Comment by grosser** [comment]
I'll see if I can improve this a bit, but either way this is better than the previous "just deploy the same sha again when it failed" logic 🤷‍♂

**Comment by grosser** [comment]
yeah it's not straightforward, so I'll leave it like it is, not worse than a manual redeploy of an old sha

**Pull request merged**
