### PR TITLE
we do not need the vanilla env config once we generate for every depl…

### PR DESCRIPTION
**Pull request by grosser**
…oy group and keeping it makes required complicated

leaving the default file means:
 - all variables need a all default -> will not see if something is missing
 - adds the possibility of screwing up by somehow picking the default

@zendesk/runway 

all our projects now use ENV.xxx.json so ENV.json can go.
for everything else you now either pick deploy groups or not, but there is no more middle ground 

### Risks
 - None

### CODE REVIEW

**Comment by sandlerr** [comment]
so the base file will continue to exist just to specify required keys?

**Comment by grosser** [comment]
exactly, everything else is filled out via samson env variables

**Comment by grosser** [comment]
+ it has service and other foobar

**Comment by sandlerr** [comment]
:+1:

**Pull request merged**
