### PR TITLE
use assert_request helper to make sure each stub is actually used

### PR DESCRIPTION
**Pull request by grosser**
@jonmoter @dragonfax

### CODE REVIEW

**Comment by bblimke** [comment]
@grosser Thank you for the suggestion.

WebMock seeps global stub and request registries, therefore the solution you have suggestion only works in some cases.

The stub_request invocation inside the block is a global declaration and the stub is available after the block as well.
At the same time the request registry is global as well, therefore any requests executed before the block will exist in that registry as well.

**Comment by grosser** [comment]
... I'm not super worried about that since my usecase is mostly "requests were actually made", but undoing the stubs would be a nice cleanup ... any api I can use to de-register the stubs ?

requests executed before the block will fail, so I'm not worried about that

**Comment by bblimke** [comment]
There is no API to unstub. It won't be hard to add a method for that, by going through WebMock::StubRegistry and removing all matching stubs.

**Comment by oliakremmyda** [comment]
@bblimke can't `remove_request_stub` api function be used for this case?

**Comment by grosser** [comment]
works, thx! :)
https://github.com/zendesk/samson/pull/2530

**Comment by grosser** [comment]
FYI made the helper behave more like rspec/mocha assertions in https://github.com/zendesk/samson/pull/2473 ... would love to see that in webmock itself :)

**Pull request merged**
