### PR TITLE
Add env var to keep images built with docker

### PR DESCRIPTION
**Pull request by rata**
/cc @zendesk/samson

### Tasks
 - [ ] :+1: from team

### References
 - Jira link:

### Risks
- Level: Low

Tested and seems to work fine here with the env var defined to 1

### CODE REVIEW

**Comment by rata** [comment]
Closes: #1043

**Comment by grosser** [comment]
.env.example docs for this setting and some docs on why/when this will be useful ?

**Comment by rata** [comment]
@grosser Oh, sorry! How about now? :)

**Comment by grosser** [comment]
❤️

**Pull request merged**
