### PR TITLE
remove weird/dangerous job UI

### PR DESCRIPTION
**Pull request by grosser**
screen shot 2017-02-06 at 3 57 54 pm

@zendesk/samson  users either do a deploy or macro or build ... don't need yet another UI to execute random commands ?

### CODE REVIEW

**Comment by jonmoter** [comment]
Have you looked through our projects to see if any teams are using Jobs right now?

**Comment by henders** [comment]
Yea, the only use I have is checking the output of previous macro executions.

**Comment by grosser** [comment]
Craig mentioned that too ... will have to somehow make macros show their
executions ... which would be good anyway ... or kill macros :D

**Comment by jonmoter** [comment]
In general, I'm wary of removing functionality that other people may be using.  I'd be upset if I updated to a newer version of an app, and some functionality that I relied upon was just gone.

**Comment by henders** [comment]
I do like the macros as they're the best way to run restarts without redeploying, so I'd shed a tear if they got removed.

**Comment by grosser** [comment]
idk of any usecase for jobs ... we can find out and then revert ... maybe
ask more zendeskians ...

we can convert macros into stages with 'no code deployed' ... that would be
fast then too ...

maybe we start with just removing the execute mechanic and see if anyone
complains ?

**Comment by grosser** [comment]
the dangerous bit is gone in https://github.com/zendesk/samson/pull/1761 ... so only thing left is linking macros to their jobs ... new PR will be simpler

**Pull request closed without merging**
