### PR TITLE
make replace work again

### PR DESCRIPTION
**Pull request by grosser**
2bf25bdfb123b4e12997ee3e49e7eee5789b955c disabled tty ... now we bring it back end support replacement during streaming

@sandlerr @mblaschke 

fix for bug found in https://github.com/zendesk/samson/pull/864

### Risks
- Low: output breaks

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:

**Comment by grosser** [comment]
💇 fixed the tty issue by using script -q ... looks sane ?

**Comment by grosser** [comment]
... wrong button

**Comment by grosser** [comment]
screen shot 2016-04-21 at 10 05 25 pm

**Comment by sandlerr** [comment]
I guess we will find out if our deploy scripts are well behaved or if they pollute the terminal output :+1:

**Comment by grosser** [comment]
requested env for PTY here ... but doubt anyone will fix it ... https://bugs.ruby-lang.org/issues/12312

**Comment by pschambacher** [comment]
👍

**Pull request merged**
