### PR TITLE
Opt in to zendesk stale bot

### PR DESCRIPTION
**Pull request by ragurney**
We have a bot running on Zendesk repos '[zendesk/stale](https://github.com/zendesk/stale)' that will automatically close stale issues and PRs. Adding this file will opt in to this bot.

/cc @zendesk/samson

### Tasks
 - [ ] :+1: from team

### CODE REVIEW

**Comment by grosser** [comment]
I'm not a big fan of these bots since they end hiding potentially valid/important issues just because the issue reporter no longer cared. Having a list of things that need to be done is kinda nice ... can add `won't fix` or close manually

**Comment by grosser** [comment]
Would rather go through them manually and see if there is anything useful
and close if not.
PR owner forgetting about things does not mean the PR is bad.

**Comment by grosser** [comment]
just the oldest 3 ... `git worktree` `gitlab hook` `remove binary builder` all good things we should do and not forget about

**Comment by dragonfax** [comment]
2 years buddy. How many years would you be happy with? Before we assume something was forgotten for a reason?

**Comment by dragonfax** [comment]
Also, keep in mind this bot already worked to a degree. The PR for this bot got you to look at those old PRs. Thats kind of the point.

**Comment by grosser** [comment]
But then the bot will just close them and I will never see them again /
forget about them.
Open PRs don't hurt anyone and might give inspiration of what still needs
to be done,
if we want to close them then the important ones should be converted to
issues, not automatically closed/forgotten.

**Comment by ragurney** [comment]
Closing

**Pull request closed without merging**
