### PR TITLE
PAAS-3357 add kritis breakglass option

### PR DESCRIPTION
**Pull request by grosser**
Screen Shot 2019-05-28 at 10 55 12 AM
Screen Shot 2019-05-28 at 10 52 13 AM

```
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: example-server
    labels:
      project: example
      role: server
      team: foo
      kritis.grafeas.io/tutorial: ''
    namespace: sdfsfsfs
    annotations:
      samson/deploy_url: http://localhost:3000/projects/example-kubernetes/deploys/515
      kritis.grafeas.io/breakglass: 'true'
```

@zendesk/compute 
/cc @zendesk/samson

### CODE REVIEW

**Comment by adammw** [comment]
Feel like this should be on an individual deploy, not the deploy group...

**Comment by grosser** [comment]
this is to disable it globally so we can roll out kritis without taking down the cluster and to turn it off in emergencies ... per deploy can come later if we need it, teams can also add it to their yaml files so the next deploy does not break again

**Comment by adammw** [comment]
in that case, shouldn't it be per kubernetes cluster instead than, rather than deploy group?

**Comment by grosser** [comment]
hmm yeah

**Comment by grosser** [comment]
updated 💇‍♂  @adammw

**Comment by hgokavarapuz** [comment]
Can you please paste the full screenshot where it appears in the Samson UI. Not clear from the current one.

**Comment by grosser** [comment]
Screen Shot 2019-05-29 at 2 14 21 PM

**Review by hgokavarapuz — APPROVED** [review]

**Pull request merged**
