### PR TITLE
TOOLS-1934 set preStop hook to prevent 502s during reboots because se…

### PR DESCRIPTION
**Pull request by grosser**
…rvers are stale for a few seconds

@jonmoter @irwaters @ilkkao @smo921 @libo

### CODE REVIEW

**Comment by libo** [comment]
Given that these 3 seconds do not solve the problem, we still see 502 during deploys, I am not sure if it's worth probably to wait to merge...

**Comment by grosser** [comment]
@libo is anyone investigating this issue ? / when can I expect an update ?

**Comment by libo** [comment]
We are seeing 502 also outside deployments so we would like to see that solved first to better understand what this is..

**Comment by libo** [comment]
I added a 10 sec today and this reduced a bit:
screen shot 2017-10-04 at 17 55 31

But this didn't removed completely. We could try 30sec but I am wondering if we had a better way then waiting? 

I also notice a lot of `kube_stats.pod_unhealthy` during deployments. I don't understand if it's supposed to be like this or symptomatic of something wrong @jonmoter ?
screen shot 2017-10-04 at 17 57 27

**Comment by grosser** [comment]
I think pod_unhealthy is expected during restart since the health checks of
the new pods would fail for a while

**Comment by grosser** [comment]
do 25s just to see if it is completely gone, but I doubt it helps ... any
theory on why it keeps happening ?

**Pull request merged**
