### PR TITLE
allow selecting no dockerfile to deploy containers with pre-selected …

### PR DESCRIPTION
**Pull request by grosser**
…images

@zenhao @jonmoter
/cc @irwaters

### CODE REVIEW

**Comment by grosser** [comment]
We already allow this if the project has no dockerfile ... But maybe we
should only allow for whitelisted repos or still build bogus images that
only have a from ... Not sure ...

**Comment by irwaters** [comment]
@jonmoter what are your thoughts on this?  Pretty sure that sec-ops is going to want everything scanned, but that's just like my opinion man.

**Comment by jonmoter** [comment]
Yeah, now that I think about it some more, we should move to a pattern where we only deploy docker images from our registry (ECR, GCR, Artifactory, whatever) that Samson is aware of. So let's not merge this change.

**Comment by grosser** [comment]
I think this is still a good usecase for others / is consistent with the current "no Dockerfile present logic" ... so we should still merge this but also add a "Only allow images built by samson" or "only allow builds from these registries" feature.

So preferably merge this and build the whitelist feature after ... alternatively keep this open and build the whitelist feature then merge this.

**Pull request closed without merging**
