### PR TITLE
capitalise first letter only

### PR DESCRIPTION
**Pull request by sandlerr**
@zendesk/samson #388

### CODE REVIEW

**Comment by princemaple** [comment]
1__ruby
Am I missing something?

**Comment by sandlerr** [comment]
@princemaple see the linked issue

**Comment by princemaple** [comment]
Probably just get rid of capitalization. If people do cases properly, we don't need it.
By doing what you do now, there are still cases like "iTunes" will end up badly.

**Comment by sandlerr** [comment]
You can just put a whitespace in front of the word if you don't want it to be capiltalised. Not a big deal in this case but prefer not to make surprising changes to existing users.

**Comment by steved** [comment]
Just remove it

**Comment by jwswj** [comment]
Agree - just remove it

**Comment by princemaple** [comment]
:+1:

**Comment by jwswj** [comment]
I like the old style. Reads easier than the ternary if. #nit

**Pull request merged**
