### PR TITLE
bundle update, kill off strange test

### PR DESCRIPTION
**Pull request by sandlerr**
- [rails 4.2.0...4.2.1](http://weblog.rubyonrails.org/2015/3/19/Rails-4-2-1-and-4-1-10-have-been-released/)
- [addressable 2.3.6...2.3.8](https://github.com/sporkmonger/addressable/blob/master/CHANGELOG.md)
- [angular-rails-templates 0.1.3...0.2.0](https://github.com/pitr/angular-rails-templates/blob/master/CHANGELOG.md)
- [bootstrap-sass 3.3.1.0...3.3.4.1](https://github.com/twbs/bootstrap-sass/blob/master/CHANGELOG.md) now provides minified bootstrap and just uses upstream dist files
- [dalli 2.7.2...2.7.4](https://github.com/mperham/dalli/blob/master/History.md)
- [dogapi 1.13.0...1.17.0](https://github.com/DataDog/dogapi-rb/blob/master/CHANGELOG.md)
- [execjs 2.2.2...2.5.2](https://github.com/rails/execjs/compare/v2.2.2...v2.5.2) some obscure runtimes dropped, new one added, started testing on MRI 2.2, should be no effect
- [faraday 0.9.0...0.9.1](https://github.com/lostisland/faraday/blob/master/CHANGELOG.md)
- [globalid 0.3.0...0.3.5](https://github.com/rails/globalid/releases) rails gem pulled in by activejob, not used
- [goldiloader 0.0.8...0.0.9](https://github.com/salsify/goldiloader/blob/master/CHANGELOG.md)
- [hashie 3.3.2...3.4.1](https://github.com/intridea/hashie/blob/master/CHANGELOG.md)
- [httparty 0.13.3...0.13.4](https://github.com/jnunemaker/httparty/compare/v0.13.3...v0.13.4) lot of refactoring, only used by flowdock here
- [json 1.8.1...1.8.2](https://github.com/flori/json/blob/master/CHANGES)
- [jwt 1.2.0...1.5.0](https://github.com/progrium/ruby-jwt/compare/jwt-1.2.0...jwt-1.5.0)
- [kaminari 0.16.1...0.16.3](https://github.com/amatsuda/kaminari/blob/v0.16.3/CHANGELOG.rdoc)
- [lograge 0.3.0...0.3.2](https://github.com/roidrage/lograge/blob/master/CHANGELOG.md)
- [loofah 2.0.1...2.0.2](https://github.com/flavorjones/loofah/blob/master/CHANGELOG.rdoc)
- [maxitest 1.3.1...1.5.0](https://github.com/grosser/maxitest/compare/v1.3.1...v1.5.0)
- [mime-types 2.4.3...2.5.0](https://github.com/mime-types/ruby-mime-types/blob/master/History.rdoc)
- [mini_portile 0.6.1...0.6.2](https://github.com/flavorjones/mini_portile/blob/master/CHANGELOG.md)
- [minitest 5.5.1...5.6.1](https://github.com/seattlerb/minitest/blob/master/History.rdoc)
- [multi_json 1.10.1...1.11.0](https://github.com/intridea/multi_json/blob/master/CHANGELOG.md)
- [mysql2 0.3.17...0.3.18](https://github.com/brianmario/mysql2/releases)
- [ngannotate-rails 0.15.4...1.0.0](https://github.com/kikonen/ngannotate-rails/compare/v0.15.4...v1.0.0) switched versioning scheme
- [nokogiri 1.6.5...1.6.6.2](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.rdoc)
- [octokit 3.7.0...3.8.0](https://github.com/octokit/octokit.rb/compare/v3.7.0...v3.8.0) blocks invalid repo strings causing a test failure
- [omniauth-oauth2 1.2.0...1.3.0](https://github.com/intridea/omniauth-oauth2/compare/v1.2.0...v1.3.0)
- [pg 017.1...0.18.2](https://bitbucket.org/ged/ruby-pg/src/94e26b472c78449cae09344e3d738722a7866b6d/History.rdoc?at=default)
- [puma 2.10.2...2.11.2](https://github.com/puma/puma/blob/master/History.txt) bunch of bug fixes
- [rack 1.6.0...1.6.1](https://github.com/rack/rack/compare/1.6.0...1.6.1)
- [rack-test 0.6.2...0.6.3](https://github.com/brynary/rack-test/blob/master/History.txt)
- rails-assets-* couldn't find sources
- [rails-dom-testing 1.0.5...1.0.6](https://github.com/rails/rails-dom-testing/releases)
- [rails-html-sanitizer 1.0.1...1.0.2](https://github.com/rails/rails-html-sanitizer/releases)
- [rails_serve_static_assets 0.0.3...0.0.4](https://github.com/heroku/rails_serve_static_assets/blob/master/CHANGELOG.md)
- [sass 3.4.9...3.4.13](https://github.com/sass/sass/blob/stable/doc-src/SASS_CHANGELOG.md)
- [sass-rails 5.0.0...5.0.3](https://github.com/rails/sass-rails/releases)
- [simplecov 0.9.1...0.10.0](https://github.com/colszowka/simplecov/blob/master/CHANGELOG.md)
- [simplecov-html 0.8.0...0.10.0](https://github.com/colszowka/simplecov-html/compare/v0.8.0...v0.10.0)
- [slack-api 1.1.0...1.1.3](https://github.com/aki017/slack-ruby-gem/compare/v1.1.0...v1.1.3)
- [sprockets-rails 2.2.2...2.3.1](https://github.com/rails/sprockets-rails/releases) actually test this version of Rails
- [sse-rails-engine 1.2.2...1.3.0](https://github.com/henders/sse-rails-engine/releases/tag/v1.3.0)
- [thread_safe 0.3.4...0.3.5](https://github.com/ruby-concurrency/thread_safe/compare/v0.3.4...v0.3.5)
- [uglifier 2.6.0...2.7.1](https://github.com/lautis/uglifier/blob/master/CHANGELOG.md)
- [web-console 2.0.0...2.1.2](https://github.com/rails/web-console/blob/master/CHANGELOG.markdown)
- [webmock 1.20.4...1.21.0](https://github.com/bblimke/webmock/blob/master/CHANGELOG.md)
- [zendesk_api 1.6.3...1.7.4](https://github.com/zendesk/zendesk_api_client_rb/compare/v1.6.3...v1.7.4)

### CODE REVIEW

**Comment by sandlerr** [comment]
@zendesk/samson anyone got a spare thumb?

**Comment by princemaple** [comment]
:+1: if ngannotate is only a version change

**Comment by sandlerr** [comment]
changes to ngannotate are also support for sprockets 3 (which we don't use) and changed syntax for `config.ngannotate` however we don't config it at all.

**Comment by princemaple** [comment]
yeah that's fine

**Pull request merged**
