### PR TITLE
show haw many mysql connections are waiting ... should always be 0 or…

### PR DESCRIPTION
**Pull request by grosser**
… we are in big trouble

@jonmoter @sandlerr

### CODE REVIEW

**Comment by sandlerr** [comment]
do we want to do it for connections that belong to the current thread?

**Comment by grosser** [comment]
This is more of an overall health indicator ... There should be only 1
connection per thread and when the request is finished it will not be
waiting

**Comment by sandlerr** [comment]
but won't this give false positives? if there is a connection waiting from another thread it'll still show up? anyway :+1: let's give it a shot

**Comment by grosser** [comment]
yes, it's not an indicator for why this thread was slow ... more like an overall system health thing like 'thread_count' ... I guess we should find a better place for this, but it's kind of nice to have that in the logs for later analysis ... maybe should be part of the progname or so ...

**Pull request merged**
