### PR TITLE
allow super admins to delete clusters

### PR DESCRIPTION
**Pull request by grosser**
screen shot 2017-08-23 at 4 16 36 pm
screen shot 2017-08-23 at 4 16 47 pm
screen shot 2017-08-23 at 4 34 08 pm
screen shot 2017-08-23 at 5 35 25 pm

### CODE REVIEW

**Comment by jonmoter** [comment]
Is this a hard-delete or soft delete?  What happens if there are DeployGroups associated with the cluster?

**Comment by grosser** [comment]
hard-delete ... their association is cleaned up
I'd prefer to keep it hard ... but add auditing ... need that for
updates/creates too ...
Could also show a usage count in the index UI ... maybe not allow deleting
used ... so many fancy features :D

**Comment by jonmoter** [comment]
How about we prevent deleting unless you remove all associations to Deploy Groups? I want to make sure that I (or someone else) don't screw up Samson by accidentally deleting a legit cluster.

**Comment by grosser** [comment]
sounds good ... also makes it obvious when a cluster is unused ... so might as well add that to the UI like commands does

**Comment by grosser** [comment]
now with all the bells and whistles ...

**Pull request merged**
