### PR TITLE
Kubernetes: auth options

### PR DESCRIPTION
**Pull request by albertrdixon**
Really simple addition to add support for authentication options in your kubeconfig

/cc @zendesk/samson

### CODE REVIEW

**Comment by grosser** [comment]
looks good ... @irwaters / @jonmoter can you check ?

**Comment by grosser** [comment]
travis is not happy though :D

`NoMethodError: undefined method `auth_options' for #<Kubeclient::Config::Context:0x0000000bfb1ae8>
`

**Comment by albertrdixon** [comment]
bah, `auth_options` is in `kubeclient >= 1.2.0` ...

**Comment by grosser** [comment]
update it ?

**Comment by albertrdixon** [comment]
bumping to `1.2.x` would make this a not so simple PR.

I guess you all were keeping it at `1.1.4` until the kubeconfig updates landed? `1.2.0` includes those changes so it would make sense to upgrade.

**Comment by grosser** [comment]
👍 looks good to me ...

**Comment by jonmoter** [comment]
Looks good to me too!

**Pull request merged**
