### PR TITLE
Ignore multiple RoleBindings

### PR DESCRIPTION
**Pull request by uthark**
**Note**: Samson is a public repo, do not include Zendesk-internal information, urls, etc.

Ignore multiple RoleBindings

### References
- Jira link: 

### Risks
- Low

### CODE REVIEW

**Comment by uthark** [comment]
cc @adammw

**Review by grosser — COMMENTED** [review]
we need to confirm no existing RoleBinding would get it's name changed by this
... maybe simpler to change a single project to use `samson/keep_name: "true"` to resolve it
once the project is migrated to namespaces these restrictions no longer apply

**Review by adammw — APPROVED** [review]

**Review by grosser — CHANGES_REQUESTED** [review]
see comment above

**Comment by uthark** [comment]
@grosser but `Role`, `ConfigMap` and `PodSecurityPolicy` are namespaced..

**Comment by grosser** [comment]
the logic is "you using namespaces ? ... k, no name change foobar for you" :)

**Comment by uthark** [comment]
Got it. So, @adammw then needs to use `samson/keep_name` annotation?

**Comment by grosser** [comment]
Either that or we need to check if it's safe to enable.

**Pull request closed without merging**
