### PR TITLE
dry up user

### PR DESCRIPTION
**Pull request by grosser**
@pswadi-zendesk @steved555 @jonmoter 

### Risks
 - None

### CODE REVIEW

**Comment by jonmoter** [comment]
I notice this adds `integration: true` as a parameter to `User.create_with`, which wasn't there before. What effect does that have?

**Comment by grosser** [comment]
hehe, yes, copy paste error :)

**Comment by grosser** [comment]
fixed, +1 ?

**Comment by jonmoter** [comment]
:+1:

**Pull request merged**
