### PR TITLE
sort project select and allow to search for global commands

### PR DESCRIPTION
**Pull request by grosser**
@zendesk/runway 

screen shot 2016-03-16 at 9 06 31 pm

### Risks
- None

### CODE REVIEW

**Comment by grosser** [comment]
@zendesk/runway review plz

**Comment by grosser** [comment]
I guess @zendesk/samson might be more appropriate ...

**Comment by sandlerr** [comment]
:+1:

**Comment by grosser** [comment]
thx for stopping by :)

**Comment by sandlerr** [comment]
Its only fair, I'm in both those github teams :)

**Pull request merged**
