### PR TITLE
bump marco polo to fix warning

### PR DESCRIPTION
**Pull request by grosser**
https://github.com/arches/marco-polo/pull/16#issuecomment-1942747103

@rsb 

### Risks
- Low

### CODE REVIEW

**Comment by rsb** [comment]
What's up with all the failing tests?

**Comment by grosser** [comment]
maybe need to require pry first or bump it too ... will revisit

**Comment by rsb** [comment]
`➜ bin/rails s
Puma starting in single mode...
* Puma version: 5.6.8 (ruby 3.0.6-p216) ("Birdie's Version")
*  Min threads: 8
*  Max threads: 250
*  Environment: development
*          PID: 33673
! Unable to load application: NoMethodError: undefined method `new' for Pry::Prompt:Module
bundler: failed to load command: puma (/Users/robert.scottbuccleuch/.rbenv/versions/3.0.6/bin/puma)
/Users/robert.scottbuccleuch/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/marco-polo-2.0.3/lib/marco-polo.rb:28:in `<main>': undefined method `new' for Pry::Prompt:Module (NoM
ethodError)
        from /Users/robert.scottbuccleuch/.rbenv/versions/3.0.6/lib/ruby/3.0.0/bundler/runtime.rb:60:in `require'
        from /Users/robert.scottbuccleuch/.rbenv/versions/3.0.6/lib/ruby/3.0.0/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/robert.scottbuccleuch/.rbenv/versions/3.0.6/lib/ruby/3.0.0/bundler/runtime.rb:55:in `each'
        from /Users/robert.scottbuccleuch/.rbenv/versions/3.0.6/lib/ruby/3.0.0/bundler/runtime.rb:55:in `block in require'
        from /Users/robert.scottbuccleuch/.rbenv/versions/3.0.6/lib/ruby/3.0.0/bundler/runtime.rb:44:in `each'
        from /Users/robert.scottbuccleuch/.rbenv/versions/3.0.6/lib/ruby/3.0.0/bundler/runtime.rb:44:in `require'
        from /Users/robert.scottbuccleuch/.rbenv/versions/3.0.6/lib/ruby/3.0.0/bundler.rb:175:in `require'
        from /Users/robert.scottbuccleuch/Code/zendesk/samson/config/application.rb:24:in `<main>'
        from /Users/robert.scottbuccleuch/Code/zendesk/samson/config/environment.rb:3:in `require_relative'
        from /Users/robert.scottbuccleuch/Code/zendesk/samson/config/environment.rb:3:in `<main>'
        from config.ru:4:in `require_relative'
        from config.ru:4:in `block in <main>'`

**Comment by grosser** [comment]
can't reproduce locally on 3.2 so I'll get that merged first and then revisit

**Comment by rsb** [comment]
Should I be testing locally on 3.2?

**Comment by grosser** [comment]
no, I just can't get 3.0 to run :D

**Comment by grosser** [comment]
rebased, should be fixed now 🤞

**Review by rsb — APPROVED** [review]

**Pull request merged**
