### PR TITLE
do not show not working auth methods

### PR DESCRIPTION
**Pull request by grosser**
@zendesk/samson 

Problem:
 - we show auth methods that do not work, leading to potential confusion
 - every new auth method will be a second-class citizen since we cannot show it by default

Solution:
 - no auth method is shown by default, everything must be enabled
 - bootstrap still still sets up the example github auth

screen shot 2016-05-31 at 10 51 06 am

# Risks
 - will disable existing samson login screens that relied on the default setup

### CODE REVIEW

**Comment by jonmoter** [comment]
👍

**Comment by jonmoter** [comment]
What's the ops change that's needed for this?  Set AUTH_GOOGLE=1?

**Comment by grosser** [comment]
ops change is in the works, waiting on merging that first

**Comment by grosser** [comment]
made `true` also mean enabled since 1 is a weird way of saying `enabled`

**Comment by grosser** [comment]
all rolled out, should be good to go :)

**Pull request merged**
