### PR TITLE
rename buddy check period to redeploy_timeout

### PR DESCRIPTION
**Pull request by grosser**
clearer to me ... @zendesk/runway 

### Risks
 - None

### CODE REVIEW

**Comment by sandlerr** [comment]
This is better than period so :+1:
Naming is hard... a redeploy sounds to me like it should go to the same target. `BuddyCheck.validity_timeout`?

**Comment by sandlerr** [comment]
`BuddyCheck.invalidate_after`?

**Comment by grosser** [comment]
valid_until ?

**Comment by grosser** [comment]
meh ... validity_timeout ... since it's used with .ago ...

**Comment by grosser** [comment]
meh ... grace_period ... at least that is consistent with the env var :D

**Comment by grosser** [comment]
looking good ?

**Comment by sandlerr** [comment]
LGTM

**Pull request merged**
