### PR TITLE
Merge pull request #254 from zendesk/roman/hotfix

### PR DESCRIPTION
**Pull request by grosser**
@sandlerr @epssy @atroche @princemaple 

### Risks
 - invalid info ... but better then dealing with nils forever ...

### CODE REVIEW

**Comment by princemaple** [comment]
Restarted the failing build.
:+1:

**Comment by sandlerr** [comment]
@grosser, there is a 10 month old lock on zendesk_reporting causing this. DB console is currently broken, so thought I'd put up a hotfix until we fix the data.

**Comment by sandlerr** [comment]
it was always supposed to be temporary, but have we fixed the issue yet?

**Comment by grosser** [comment]
yes, a long time ago afaik :)

**Pull request merged**
