### PR TITLE
Risks no longer required to be last section

### PR DESCRIPTION
**Pull request by ibrahima**
* The risks section of the PR can now be followed by other sections
* Added unit tests for this case

/cc @zendesk/samson

### Tasks
 - [ ] :+1: from team

### References
 - Jira link:

### Risks
- Level: Low

### CODE REVIEW

**Comment by ibrahima** [comment]
As a side note, I noticed the use of Rails' strip_heredoc in some of the specs. As of Ruby 2.3 you can now use squiggly heredocs to avoid needing that: https://infinum.co/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc

**Comment by grosser** [comment]
ah yes plz ... want to make another PR ? :)

**Comment by grosser** [comment]
ideally the risk regexp would be smart enough to stop at headers ... but that might be tricky ... good enough and we have the tests if we ever want to refactor ...

just merge ahead on green ...

**Comment by ibrahima** [comment]
Cool cool. Yeah, I thought about making that regexp do more, but I think I'd personally prefer more readable code than a concise but hard to read regex.

**Comment by ibrahima** [comment]
Oh hold on a sec, I'll update the docs too.

**Comment by ibrahima** [comment]
Should be good to go now!

**Comment by grosser** [comment]
🎉

**Pull request merged**
