### PR TITLE
allow setting a docker registry namespace

### PR DESCRIPTION
**Pull request by grosser**
@zendesk/paas @rata

### CODE REVIEW

**Comment by rata** [comment]
Not sure I understand the use case. Is this to have a (registry, repo) per stage (like prod, staging, etc.) and be the repo named like: registry/stage/permalink_base?

**Comment by rata** [comment]
But it seems fine! :+1:

**Comment by grosser** [comment]
to have a namespace like samson or test or apps that can have finer access control / not mess with everything else

**Comment by rata** [comment]
Perfect :)

**Comment by jonmoter** [comment]
For example, we want to have a repositories like registry.zendesk.blah/official/* that are only writeable by Samson, but registry.zendesk.blah/dev/* that can be written to by any developer.

👍

**Pull request merged**
