### PR TITLE
newer vault server no longer gets read as json

### PR DESCRIPTION
**Pull request by grosser**
https://github.com/hashicorp/vault-ruby/issues/88

### CODE REVIEW

**Comment by grosser** [comment]
@irwaters @jonmoter

**Comment by sethvargo** [comment]
I've tried really hard to reproduce the incorrect content-type header, and I'm not seeing it. Do you have something different in your setup?

What's the use case for `to_h` - yes it was removed, but it was not an API that was actually by-design (it was a by-product of having inherited from Struct)

**Comment by grosser** [comment]
hmm the to_h patch should be be here ... turned that into a separate PR ...
if it's not a common issue then the header thing is most likely some custom issue on our end :(
... I'll update if we find it ...

**Comment by mfischer-zd** [comment]
@sethvargo the root cause was https://github.com/hashicorp/vault/issues/1791 (incorrect Content-Type response header when using request forwarding), which will be fixed in Vault 0.6.2.

**Comment by sethvargo** [comment]
Ah - okay. I had a feeling it was either: 1. Haproxy/load balance doing some weirdness or 2. the request forwarding

**Comment by dragonfax** [comment]
👍

**Pull request merged**
