### PR TITLE
Update Rails (4.2.7.1) and Webmock (2.1.0)

### PR DESCRIPTION
**Pull request by apanzerj**
* Update Rails and webmock

/cc @zendesk/samson

### Tasks
 - [ ] :+1: from team

### Risks
- Level: Low

### CODE REVIEW

**Comment by apanzerj** [comment]
@jonmoter this is a simple one to take out of the PR

**Comment by apanzerj** [comment]
@grosser

**Comment by grosser** [comment]
👍

**Comment by apanzerj** [comment]
Thanks

**Pull request merged**
