### PR TITLE
PAAS-339 allow users to see some secrets

### PR DESCRIPTION
**Pull request by grosser**
we have lots of secrets that are not really secret ... so allow to show them

also storing creator_id for vault backend

@irwaters @jonmoter 

screen shot 2016-08-18 at 1 50 44 pm
screen shot 2016-08-18 at 1 49 38 pm

### CODE REVIEW

**Comment by irwaters** [comment]
wfm 👍

**Comment by grosser** [comment]
confirmed working in master :D 

screen shot 2016-08-18 at 2 14 50 pm

**Comment by jonmoter** [comment]
Suggestion: add a tooltip or bit of text explaining what the "Visible" checkbox does in the UI, 'cause it's not immediately obvious to me with that word.

Otherwise 👍

**Comment by grosser** [comment]
added `title: 'Value visible in samson edit UI'`

**Pull request merged**
