### PR TITLE
correctly fetch data when it is an ActionController::Parameters object

### PR DESCRIPTION
**Pull request by anthonywoo**
When we moved to rails 5 - `params` is no longer a hash and is now an `ActionController::Parameters` object. Since it is now this object - when we pass in `params` to `Sawyer` (to get `@data`) it preserves the object type and calling method notation on the Sawyer resource no longer works.

I tried to look into converting `params` to a hash before we create the `Sawyer` resource using `params.permit()` however - that proved to be very difficult when dealing with webhook data

I am open to suggestions if anyone has a better idea on how to convert `ActionController::Parameters` to a hash

/cc @zendesk/samson

### Tasks
 - [ ] :+1: from team

### References
 - Jira link:

### Risks
- Level: Low. Github Pull request Integration may still be broken...

### CODE REVIEW

**Comment by grosser** [comment]
the reason we did not see this was missing tests ... so let's add one that fails without these changes :)

**Comment by sandlerr** [comment]
> I am open to suggestions if anyone has a better idea on how to convert `ActionController::Parameters` to a hash

Would this be suitable? http://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-to_h

**Comment by anthonywoo** [comment]
> Would this be suitable? http://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-to_h

I was looking to use that method - but it only returns permitted keys which I thought might be a hassle to permit all keys we need from the github webhook. Will take a 2nd look at it though as it seems cleaner

**Comment by anthonywoo** [comment]
💇 @grosser @sandlerr added a test - although it would've been difficult to detect this type of change when we upgraded to rails 5 as the `params` object changed from a hash and we assumed it was a hash in our tests

Also rubocop is failing on something not related in this PR - is it ok to ignore it? (Or I can increase the `LineLength` cop 😄 )

**Comment by grosser** [comment]
@dragonfax caused that ... plz fix the line here so we get back our green master :)

**Comment by grosser** [comment]
👍

**Comment by sandlerr** [comment]
There's also a `to_unsafe_h` method that returns an unfiltered version

**Comment by irwaters** [comment]
You can also do a to_unsafe_h, then a to_h on that….

**Comment by anthonywoo** [comment]
Thanks! `.to_unsafe_h` was what I was loooking for!

**Comment by grosser** [comment]
👍

**Pull request merged**
