### PR TITLE
highlighted lines a bit like github

### PR DESCRIPTION
**Pull request by sandlerr**
cc @zendesk/vegemite @jden @zendesk/samson 

### Description

* Add description here
* Add any screenshots if you are touching the UI
* Remember to add unit tests

/cc @zendesk/samson

Inspired by Github. Highlights and scrolls to lines that are in the fragment on page load or clicked (and shift-clicked). If my choice of colour scheme offends anyone (or we use text that will be hard to read on that background) please shout out in this PR or submit another to change it. AFAIK we mostly only have white and red text.

screen shot 2016-04-06 at 1 01 53 pm

### References
* #790 

### Risks
* [medium] JS errors on the deploy page

### CODE REVIEW

**Comment by grosser** [comment]
:+1: so fancy :D

**Comment by sandlerr** [comment]
I don't have my normal SIM card, can't 2FA into codeclimate. Would be good if anyone can paste the error here, otherwise I can fix it next week.

**Comment by grosser** [comment]
screen shot 2016-04-05 at 11 37 30 pm

**Comment by sandlerr** [comment]
Thanks @grosser codeclimate is green now, +1 to merge?

**Comment by jonmoter** [comment]
Nicely done!  :+1:

**Comment by jden** [comment]
:tada: awesome!

**Comment by grosser** [comment]
makes it jump to the line when clicked ... kind of annoying ...

**Comment by grosser** [comment]
also looks like it makes all lines print to a single line ... reverted it to get back to a working version

**Pull request merged**
