### PR TITLE
allow inlining association attributes for idempotent api updates

### PR DESCRIPTION
**Pull request by grosser**
for https://github.com/zendesk/samson/issues/3172

@zendesk/bre

### CODE REVIEW

**Comment by danihodovic** [comment]
I'll give this a try. Is it possible to inline **all** related entities instead of having to specify what you want?

**Comment by danihodovic** [comment]
So I could theoretically read the upstream webhooks and read the webhooks the user has provided, see how the state diffs and update based on that, but I don't think it's good DX. It would either require the user to specify a webhook ID up front (so that a new webhook isn't created) or I would have to perform some magic in the Ansible module to compare webhook attributes and if a webhook with the parameters doesn't exist create one.

Both of these solutions are not good enough because specifying `slack_webhook_attributes: []` in a PUT or a PATCH does not remove the existing webhooks, since the Slack webhooks are their own DB entity. The UI sort of hacks around this by specifying a property called `_delete` nested inside of the Slack webhook to remove a webhook. This isn't great when dealing with the API directly.

I think we should either ensure that PUTs replace the entire stage (including all the nested sub-resources) or separate Slack webhooks so that they're a  REST resource with it's own endpoints.

**Comment by danihodovic** [comment]
I'm also a little confused of the difference between PUT and PATCH. I imagined that PUT would replace the resource entirely while PATCH would work similar to json-patch, i.e update individual attributes in place.

**Comment by grosser** [comment]
- patch and put are the same in rails, just aliased
 - rebuilding something that assigns associations without checking ids sounds dangerous/complicated
 - we can have an api controller without the UI actually using that 🤷‍♂️

**Comment by grosser** [comment]
... having separate rest resource get's us into trouble with "who has access to this" duplication :/

**Comment by grosser** [comment]
I'm also open to making it return all associations that can be assigned, we just need to sanity-check that there are no secrets in the settings ...
so ideally you could figure out some client logic that stores the extra ids that get returned ...

**Comment by danihodovic** [comment]
Is it possible to return these properties on any method? After a PUT I'll need to perform another GET instead of just reading the returned payload.

**Comment by grosser** [comment]
yeah, that's all the same `render_as_json` logic ... so it's possible to do wherever

**Comment by grosser** [comment]
... so sounds like what you really need is either apis for all associations or assignable arrays without ids.
... assignable arrays could be pretty simple hack and reusable for other projects, so I'll give that a try
.

**Comment by danihodovic** [comment]
@grosser I don't want to enforce design on the API just so that it can suite my little Ansible module ;) . More complex infra-as-code tools such as Terraform can likely work around this because it can save state between runs.

If you think assignable arrays might solve the problem and doesn't impose too many changes in the API go for it. I'm not really sure what you mean by assignable arrays - but would something like this allow the stage attributes to be updated in place (including deleting webhooks)?

**Comment by grosser** [comment]
If you find nice Ansible pattern that would be preferable ... or how
terraform does this ...
I want samson to be usable by terraform mostly since we also use that
internally
assignable array would mean that we update all attributes that come in and
delete the ones that do not exist
hooks = [{url: foo}, {url: bar}]
... but I guess that would produce a lot of updates if something from the
middle was missing and then all other hooks would be updated ...
so maybe independent api is best ... but it's some boilerplate + new
routing, so not fun :)

**Comment by danihodovic** [comment]
> ... but I guess that would produce a lot of updates if something from the middle was missing and then all other hooks would be updated ...

This is implying that a stage would have many webhooks. I suspect that 99% of the use cases people have 1 or 3 webhooks active, usually to a deployment channel.

**Comment by grosser** [comment]
yes, but it's a bad pattern to build if it cannot scale :)

**Pull request closed without merging**
