### PR TITLE
allow replacing paths that themselves include a /

### LINKED ISSUE #3167: set_env_via_json with kube2iam causes kubernetes manifest to be invalid
We'd like to use [Kube2iam](https://github.com/jtblin/kube2iam) for having pods assume roles - and different roles per stage, which makes it a great fit for `set_env_via_json`.

The syntax for using kube2iam with a deployment, is setting 

```
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: iam-arn
```
and using that with `set_env_via_json`, gives the follow manifest:

```
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    annotations:
      samson/set_via_env_json-spec.template.annotations.iam.amazonaws.com/role: IAM_ROLE
```
Looking at the release doc in samson, I can verify that the variable substitution has happened correctly, see [this gist](https://gist.github.com/nayena/bb88c319df86c3e79ec5c67a209b3eea) for full release doc.

Unfortunately, this throws the following error:

```
[15:34:55] JobExecution failed: Kubernetes error feed-management-operations datapipeline Data Pipeline Stage: Deployment.apps "feed-management-operations" is invalid: metadata.annotations: Invalid value: "samson/set_via_env_json-spec.template.annotations.iam.amazonaws.com/role": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
```

### PR DESCRIPTION
**Pull request by grosser**
fixes https://github.com/zendesk/samson/issues/3167

```
[15:34:55] JobExecution failed: Kubernetes error feed-management-operations datapipeline Data Pipeline Stage: Deployment.apps "feed-management-operations" is invalid: metadata.annotations: Invalid value: "samson/set_via_env_json-spec.template.annotations.iam.amazonaws.com/role": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
```

@zendesk/compute

### CODE REVIEW

**Review by hgokavarapuz — APPROVED** [review]

**Comment by yizhang-zen** [comment]
👍 when 🍏

**Comment by grosser** [comment]
fixed and tested it with https://github.com/samson-test-org/example-kubernetes/commit/10c9085557fac94d60bd79f60aad2728faf1fdc2

@nayena can you check if this works ?

**Comment by nayena** [comment]
Yes, I will go right ahead and test it. Is it pushed to same dockerhub image `zendesk/samson:multislash`?

**Comment by grosser** [comment]
pushed it
now sha256:92276831ed76e66eecd157d516cc9565cb0f393bcdffac0a920843904fdb9003

**Comment by nayena** [comment]
It very much works! :tada:

**Pull request merged**
