### PR TITLE
put the project name into the flowdock message

### PR DESCRIPTION
**Pull request by sandlerr**
/cc @zendesk/quokka @zendesk/samson

### CODE REVIEW

**Comment by jonmoter** [comment]
While you're editing that line, could you change the call to action, so it says "Review this deploy" rather than "Approve this deploy"?

Compliance would be happier with that wording.

**Comment by sandlerr** [comment]
@jonmoter done

**Comment by adammw** [comment]
:+1:

**Comment by danielbreves** [comment]
:+1: :boom:

**Pull request merged**
