### PR TITLE
rails assets source block

### PR DESCRIPTION
**Pull request by sandlerr**
cc @zendesk/samson

### CODE REVIEW

**Comment by grosser** [comment]
:+1: 

did you try deploying that ?

**Comment by sandlerr** [comment]
Good point, I'll make sure our bundler is clever enough and then merge.

**Comment by sandlerr** [comment]
hit this bug: https://github.com/rails-assets/rails-assets/issues/225 as we are 1.8.3

**Comment by sandlerr** [comment]
deploys are failing, not sure I understand why.

**Comment by sandlerr** [comment]
deploys are failing for an unrelated reason, merging

**Pull request merged**
