### PR TITLE
pass in project to new deploy for changeset

### PR DESCRIPTION
**Pull request by sandlerr**
Fix airbrake: https://zendesk.airbrake.io/projects/95346/groups/1832043558530917221?tab=occurrences

cc @zendesk/samson

### CODE REVIEW

**Comment by sandlerr** [comment]
unfortunately the `changeset` method is stubbed

**Comment by grosser** [comment]
... that means this action had no tests ? ... add one ? :)

**Comment by sandlerr** [comment]
it has a test, but `deploy.changeset` is stubbed, which is where the error is coming from.

**Comment by grosser** [comment]
👍 damn stubs :/

**Pull request merged**
