### PR TITLE
add webhook for gitlab

### PR DESCRIPTION
**Pull request by easylo**
step 1 in integration with gitlab : webhook support 
make with : @jebovic & @infogenie

### CODE REVIEW

**Comment by steved** [comment]
Can you add a basic test in the style of the [github test](https://github.com/zendesk/samson/blob/master/test/controllers/integrations/github_controller_test.rb)?

**Comment by g3d** [comment]
+1 for that

**Comment by easylo** [comment]
work in progress, for adding test

**Comment by xakraz** [comment]
+1 also :) Can't wait for that feature !

**Comment by grosser** [comment]
then make it happen ... just a few tests and this should be good ...

**Comment by machei** [comment]
accept changes what wrote by @easylo

**Comment by grosser** [comment]
recently reworked how integrations are tested, should be super easy now to set this up ... in case anyone still wants this merged

**Comment by gsmethells** [comment]
+1

**Pull request closed without merging**
