### PR TITLE
Add Description and Contact Info fields to projects.

### PR DESCRIPTION
**Pull request by dragonfax**
Needed for ease of security audits.
https://zendesk.atlassian.net/browse/INFR-822

Project Edit Form

Project Overview

@zendesk/samson 
cc @pswadi-zendesk @lcore

### CODE REVIEW

**Comment by pswadi-zendesk** [comment]
Lets not add this additional info on the overview page.  This will be visible in the settings page for the people who are interested in it.

**Comment by dragonfax** [comment]
Can everyone view the settings page or only those that have privileges on
that project? After all, this is info for people not "on" the project.

**Comment by pswadi-zendesk** [comment]
This information is for audit purpose and will be viewed by folks who have
admin access and they will have access to Settings page.

**Comment by dragonfax** [comment]
Removed the overview tab changes.

**Comment by pswadi-zendesk** [comment]
:+1:

**Comment by jwswj** [comment]
:+1:

**Pull request merged**
