### PR TITLE
ignore outofcpu and outofmemory events

### PR DESCRIPTION
**Pull request by uthark**
Ignore `OutOfcpu` and `OutOfmemory` events.
### References
- Jira link: 

### Risks
- Low/Med/High: thing that could happen

### CODE REVIEW

**Review by eatwithforks — APPROVED** [review]

**Comment by grosser** [comment]
I don't think this helps ... we filter them out by checking `@pod.waiting_for_resources?`

**Comment by uthark** [comment]
If we fitler them out, then why in error logs we see `OutOfCpu`?That was the only error event.

**Comment by grosser** [comment]
not sure ... but sounds like there is a different bug then 🤷 <-> last PR did not work

**Comment by grosser** [comment]
ah... I think what happens is that samson is no longer in the 'getting ready' but 'verify it is stable' phase ... so something being 'pending' makes it fail

**Comment by grosser** [comment]
hmm no, example deploy was still getting ready ... digging ...

**Comment by grosser** [comment]
... yeah it stopped on `phase == 'Failed'`

**Comment by grosser** [comment]
... so would need to say "if pod is failed < 5 min ago && out-of-cpu" then treat it like "waiting for resources"

**Comment by grosser** [comment]
solved by https://github.com/zendesk/samson/pull/3779

**Pull request closed without merging**
