### PR TITLE
Change coverage to get private repo green

### PR DESCRIPTION
**Pull request by sandlerr**

### CODE REVIEW

**Comment by sandlerr** [comment]
@danielbreves @grosser this would be red if the uncovered count was not correct wouldn't it?

**Comment by danielbreves** [comment]
👍

**Comment by grosser** [comment]
it is only red if the uncovered count is higher then expected ...

should add a comment here to say with it's `3` ...

**Comment by sandlerr** [comment]
@ben @grosser does this look OK by you?

**Comment by sandlerr** [comment]
@zendesk/samson I'm not sure why this was green previously, we get coverage errors in the travis script for a private repo.

**Comment by grosser** [comment]
👍

**Pull request merged**
