### PR TITLE
track when projects finish so we can show build duration

### PR DESCRIPTION
**Pull request by grosser**
screen shot 2017-01-18 at 10 00 05 am

### CODE REVIEW

**Comment by jonmoter** [comment]
Do we distinguish between when a deploy was created, and when it started?  For example, if you create a deploy at 10am, but you don't get a buddy approval 'til 10:15am, do we save 10:15am in some column?

**Comment by grosser** [comment]
the build will be created when he deploy starts, so it will not depend on
buddy approval

atm we don't do reporting on it, so I'm not indexing it ... but yeah might
be interesting later on to build some graphs with this ...

**Comment by jonmoter** [comment]
Ah yes, this is just for `Build` objects.

Should we also add a `finished_at` column for `Deploy` and/or `Job`?

**Comment by grosser** [comment]
for deploy we use started_at and updated_at and already display duration
 ... for builds we need a finished at because it can be updated

**Comment by jonmoter** [comment]
Okay.  Using `updated_at` to mean finished at feels hacky to me.  Like if we ever run a script that updates a bunch of old Deploys, we'll lose the information about how long they took to run.

**Comment by grosser** [comment]
Yeah true ... but I'll make that it's own PR

**Comment by grosser** [comment]
confirmed working on staging

**Pull request merged**
