### PR TITLE
dont crash with keyerrors for not found jenkins things

### PR DESCRIPTION
**Pull request by sandlerr**
@zendesk/samson 

followup to https://github.com/zendesk/samson/pull/1255 which got further but caused https://zendesk.airbrake.io/projects/95346/groups/1769235950179132364/notices/1769235955706545648

### CODE REVIEW

**Comment by grosser** [comment]
test ?

... I guess :+1: ... but looks weird to do `fetch x, x` :D

**Comment by grosser** [comment]
maybe do a `if status.include?(" "); x = warning, message = status` or so to have a cleaner if/else case ...

**Comment by sandlerr** [comment]
can I please get one more :+1:, then will merge and deploy this

**Comment by grosser** [comment]
:+1:

**Pull request merged**
