### PR TITLE
make rendering index faster when user has no stars

### PR DESCRIPTION
**Pull request by grosser**
/cc @jonmoter @sandlerr 

atm it's crazy slow since we render so much stuff for all our projects ... no need for that ...

### CODE REVIEW

**Comment by grosser** [comment]
last will keep things interesting ... first would just mean same old stale repos :D 
... maybe simplest to do "Star projects to see them here" ...

**Comment by sandlerr** [comment]
or auto-star a randomised subset of projects for new users + backfill :D

**Comment by grosser** [comment]
nah ... fake data is always trouble :D

**Comment by grosser** [comment]
changed from 'Dashboard' to
screen shot 2017-02-01 at 5 21 07 pm

... this should things easier to understand ...

**Pull request merged**
