### PR TITLE
Style change, fix #153

### LINKED ISSUE #153: Buttons get messed up in a narrower browser window.
image

from: @halcyonCorsair

### PR DESCRIPTION
**Pull request by princemaple**
@pswadi-zendesk

### CODE REVIEW

**Comment by princemaple** [comment]
cc @zendesk/samson

**Comment by princemaple** [comment]
@sandlerr

**Comment by sandlerr** [comment]
Does this move the buttons slightly to the left?

**Comment by princemaple** [comment]
Nope, it has `pull-right`, not "moved". It will no longer limit the width of the container of the buttons, so the buttons can be on the same line. Effectively yes, though.

**Comment by princemaple** [comment]
#153 imagine this works as expected.

**Comment by sandlerr** [comment]
Just tried this in dev tools. It does move the buttons to the right which is what I originally meant. They don't line up with the edge of the terminal output.

**Comment by princemaple** [comment]
OK will check again later.

**Comment by princemaple** [comment]
@sandlerr Fixed

first_deploy__running__-_p1

**Comment by sandlerr** [comment]
so the overhang was caused by the negative margins on `row`? They're often quite inconvenient. :+1:

**Comment by princemaple** [comment]
Yeah you have to go full bootstrap to avoid any possible trouble.

**Pull request merged**
