### PR TITLE
long branch names break the ui

### PR DESCRIPTION
**Pull request by grosser**
screen shot 2016-01-28 at 5 21 49 pm

@jonmoter 

### Risks
 - None

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:

**Comment by sandlerr** [comment]
although as @adammw said we should do this in css

**Comment by grosser** [comment]
screen shot 2016-01-28 at 7 47 33 pm

all css now :)

**Comment by sandlerr** [comment]
awesome, thanks!

**Comment by adammw** [comment]
nice, thanks :+1

**Pull request merged**
