### PR TITLE
allow multiple deployments even though they are not properly supported

### PR DESCRIPTION
**Pull request by grosser**

### CODE REVIEW

**Comment by jonmoter** [comment]
Actually, I don't think this is it.  We want to allow > 1 container in a the spec of a single Deployment.  Isn't this validating whether there's more than 1 Deployment in a config file?

**Comment by jonmoter** [comment]
We want to remove the check in `DeployYaml#container`.

```
    def container
      containers = template.spec.template.try(:spec).try(:containers) || []
      if containers.size != 1
        raise Samson::Hooks::UserError, "Template #{@doc.template_name} has #{containers.size} containers, having 1 section is valid."
      end
      containers.first
    end
```

That's the problematic check.

**Comment by grosser** [comment]
yes, got that mixed up :D

**Comment by grosser** [comment]
updated!

**Comment by jonmoter** [comment]
👍 on 💚

**Pull request merged**
