### PR TITLE
stop people from deleting all tokens

### PR DESCRIPTION
**Pull request by grosser**
Screen Shot 2020-12-31 at 3 25 17 PM

@zendesk/compute @zendesk/eng-productivity

### CODE REVIEW

**Review by uthark — APPROVED** [review]

**Comment by adammw** [comment]
oof.. would make more sense to have a red button with a js confirm that tells them what it will do/mean, rather than expand that column unnecessarily

**Comment by adammw** [comment]
also doesn't "stop" them, just warns them so pr title is wrong

**Comment by grosser** [comment]
nobody reads confirms, we already learned that the hard way :D

**Comment by adammw** [comment]
bitmoji

**Pull request merged**
