### PR TITLE
SAMSON-222 fail validations when deploy groups is used but no group i…

### PR DESCRIPTION
**Pull request by grosser**
screen shot 2016-04-06 at 5 51 47 pm

@zendesk/samson

### CODE REVIEW

**Comment by jonmoter** [comment]
Let's say a user edits a Command, changing it from `cap production deploy` to `cap $DEPLOY_GROUPS deploy`.  That saves the Command. Does it run validations on every Stage that includes that Command?

Or does adding a Command to a Stage trigger the validations of the Stage itself?

I was thinking that rather than making this a validation on the Stage or Command, just display a warning on the deploy screen if it sees that string in the commands it's about to run, but no deploy groups are specified.

If it's a warning, then you don't have the false positive of having an error if someone just put `$DEPLOY_GROUPS` in a comment, or if they really do want to run the command even though it's empty.

**Comment by grosser** [comment]
I think the issue is most common when editing a stage, but also showing it on the deploy show page would catch even more issues ...
I don't think there will be false-positives ... printing the $DEPLOY_GROUPS is not really a valid usecase ...

**Comment by jonmoter** [comment]
FYI, it looks like there are currently 4 stages that fail this check:

```
irb(main):002:0> class Stage
irb(main):003:1>   def invalid_deploy_groups?
irb(main):004:2>     DeployGroup.enabled? && deploy_groups.empty? && command.include?("$DEPLOY_GROUPS")
irb(main):005:2>   end
irb(main):006:1> end
=> :invalid_deploy_groups?
irb(main):007:0> missing = Stage.includes(:deploy_groups).each_with_object({}) { |stage, hash| hash[stage.id] = stage if stage.invalid_deploy_groups? } ; missing.count
=> 4
irb(main):009:0> missing.values.each { |stage| puts [stage.project.name, stage.name].join(' - ') }
ultragrep - test-drdb
JIG - Staging Restart
Embed Key Registry - Production
Knowledge Bank Client - Production build
```

**Comment by jonmoter** [comment]
We talked about it. Will keep the validations, and add a warning on the "new Deploy" screen if this scenario is detected.

**Comment by grosser** [comment]
screen shot 2016-04-07 at 10 53 54 am

**Comment by jonmoter** [comment]
The "Stage" is unnecessary and awkward in that warning message.

Suggestion for text: "This stage contains at least one command using the $DEPLOY_GROUPS environment variable, but there are no Deploy Groups associated with this stage. This is probably an error."

**Comment by grosser** [comment]
Has to start with Stage, since the error is added to :stage
"This is probably an error."  could be added to every validation ... so
it's kind of redundant.

**Comment by grosser** [comment]
"Validation failed: Stage contains at least one command using the $DEPLOY_GROUPS environment variable, but there are no Deploy Groups associated with this stage."

**Comment by jonmoter** [comment]
:+1: on :green_heart:

**Comment by grosser** [comment]
FYI found a bug where we would load .env in test mode anyway because we still had dotenv-rails in the Gemfile

**Pull request merged**
