### PR TITLE
Fix docker job status

### LINKED ISSUE #1150: Docker Job Status is shown as failed even when it runs ok
Hi,

I'm using samson on tag 771 and the build status is always shown as failed when it finishes okay. The container is created okay and the image is pushed just fine, but the ```Docker Job Status: failed``` is shown on the `builds` tab (and when entering the build and seeing the details).

The build can be deployed just fine when it finished okay (although it is marked as failed), but the status is shown incorrectly.

This happens in our older version of samson too. We are using docker 1.11.2 to build docker images (so the output is from that docker version) and we are not using kubernetes remote job for building.

Do you see it too? Can I ask which docker version are you using? It's not easy for us to try another version, as it was hitting a kernel bug :-/

### PR DESCRIPTION
**Pull request by rata**
/cc @zendesk/samson

### Tasks
 - [ ] :+1: from team

### References
 - Jira link:

### Risks
- Level: Low

Fixes #1150

### CODE REVIEW

**Comment by grosser** [comment]
hmm it's false if we don't push ?

**Comment by rata** [comment]
On Mon, Jul 25, 2016 at 01:54:05PM -0700, Michael Grosser wrote:
> hmm it's false if we don't push ?

I thought you wanted that. `true` is better? :)

**Comment by grosser** [comment]
I'd think so ... if we don't want to push it's still successful ...

Did you try adding a test ?

**Comment by rata** [comment]
@grosser fixed the styling issue, but not sure how to properly write tests (never done that before). Found the `test/models/docker_builder_service_test.rb` file and tried to hack something based on what already is there, but didn't make it work :-/

**Comment by grosser** [comment]
added tests https://github.com/zendesk/samson/pull/1164

**Pull request closed without merging**
