### PR TITLE
Show the template icon where the stage name is shown.

### PR DESCRIPTION
**Pull request by dragonfax**
Lets use the template icon for stages, everywhere in Samson.

/cc @zendesk/samson @grosser

### References
 - Jira link: https://zendesk.atlassian.net/browse/TOOLS-940

### Risks

None

### CODE REVIEW

**Comment by grosser** [comment]
feels like overkill to me ... can we reduce it to places where being a template matters ? ... like the deploy group page ?

**Comment by dragonfax** [comment]
@pswadi-zendesk Asked for this. Lets hear what he thinks.

**Comment by dragonfax** [comment]
@pswadi-zendesk bump.

**Comment by pswadi-zendesk** [comment]
The template icon will be useful in the top level projects page, individual projects page where all the stages are shown. Lets go with those for now.

**Comment by dragonfax** [comment]
Well thats what we have already, so I'm closing this PR then.

**Pull request closed without merging**
